### ISSUE TITLE
Lnaguage titles not right and cannot switch language

### ISSUE THREAD

**Issue by milenmk** [tomatophp/filament-translations#12]
With the last version of the module, the Language names in the dropdown are odd

![Screenshot 2024-06-26 144520](https://github.com/tomatophp/filament-translations/assets/4587305/101b4a9d-3a86-42a9-84ba-de21c6e44f02)

Also, when trying to switch the language nothing happens. It stays EN. Is there a way to debug this, because there are no errors in the LOG file?

**Comment by 3x1io** [comment]
because it's not an error, you just need to add these keys to the translation file.

```bash
php artisan vendor:publish --tag="filament-translations-lang"
```

inside the lang 

```php
return [
"lang" => [
 "de" => ""
]
];
```

**Comment by milenmk** [comment]
I made it show the correct string. However, the command makes `lang` dir inside `app` folder, instead of in the root of the project, so I've copied the published `vendor/filament-translations` to the root `lang` dir.

However, I am still not able to switch language. Any clue how to debug this?

**Comment by 3x1io** [comment]
okay I will check it thanks for your report

**Comment by Sze-Huang** [comment]
> I made it show the correct string. However, the command makes `lang` dir inside `app` folder, instead of in the root of the project, so I've copied the published `vendor/filament-translations` to the root `lang` dir.
> 
> However, I am still not able to switch language. Any clue how to debug this?
> 
> I have `lang` column in the users table and it is added to the fillable properties of the model.

I think the lang path is still wrong? I had moved the app/lang/vendor folder from app/lang to app/resources/lang/vendor, and it finally works.

**Comment by ugurtasar** [comment]
here is fix:

php artisan vendor:publish --tag="filament-translation-component-lang"
