### ISSUE TITLE
Call to undefined method TomatoPHP\FilamentTranslations\FilamentTranslationsPlugin::getLanguageSwitcherView()

### ISSUE THREAD

**Issue by streeboga** [tomatophp/filament-translations#21]
https://github.com/tomatophp/filament-translations/blob/master/src/FilamentTranslationsPlugin.php

<img width="756" alt="Снимок экрана 2024-08-08 в 18 19 53" src="https://github.com/user-attachments/assets/244eff60-686a-46f7-aa73-caceba6b552a">

**Comment by 3x1io** [comment]
fixed on the last version.
