### ISSUE TITLE
bug: import command doesn't work as expected

### ISSUE THREAD

**Issue by mohssineAboutaj** [tomatophp/filament-translations#22]
When i ran the `php artisan filament-translations:import` it worked but it didn't respect the list of **Languages** that I set in the **config**

and here is my config
![image](https://github.com/user-attachments/assets/85977ebe-8b05-47cb-8cb2-3b13e456c0c3)

Here is the result
![image](https://github.com/user-attachments/assets/079d2093-43ff-41de-adff-71fa7f17a19b)

am I wrong or is this ok?

**Comment by 3x1io** [comment]
hi @mohssineAboutaj do you try to clear the cache after changing the config?

**Comment by AiAe** [comment]
I think i face similar issue, after update 1.0.19 and above there is new modal which loads the default config file from the library, and ignores the one thats exported and modified. 
Screenshot from 1.0.19 and upwards
![CleanShot 2024-08-27 at 2  39 49](https://github.com/user-attachments/assets/c628321c-24b9-482b-be7d-e99526c7725b)

Screenshot from 1.0.18 and above
![CleanShot 2024-08-27 at 2  40 14](https://github.com/user-attachments/assets/9e0cbfa5-aa99-4fa5-b5a4-14574f740e91)

**Comment by 3x1io** [comment]
@AiAe okay I think the component breaks. The translation, but I will try to make it work fine in the next version. thanks for your report

**Comment by Baspa** [comment]
My translations are broken as well (working on latest version). Are you already working on a solution? Else I might fix it myself and make a PR @3x1io

**Comment by 3x1io** [comment]
You can make a PR if you like

**Comment by 3x1io** [comment]
it's find now you can check the last version
