### ISSUE TITLE
Feature Request: Only populate empty translations with Google or OpenAI

### ISSUE THREAD

**Issue by dave-mills** [tomatophp/filament-translations#24]
I really like the ability to use Google Translate or OpenAI to update your translation strings. After testing it, it looks like it will update *every* string for the language you select.

This is ok as an option, but I have projects that get regularly updated, so I'll often have a bunch of translations that are checked and approved, and also a set of new strings to translate (or, rather, all languages are identical). I want to be able to ask for auto-translations for the new entries without changing any of the approved / finalised ones.

**Comment by 3x1io** [comment]
hi @dave-mills it's a good idea i will try to add it on the next version.

**Comment by dave-mills** [comment]
Thanks! I was tinkering with ideas last week. If I get something working for my project, should I share a PR?

**Comment by 3x1io** [comment]
yes i will be great

**Comment by 3x1io** [comment]
check the last version.
