### ISSUE TITLE
The resource needs a way to control the shouldRegisterNavigation value

### ISSUE THREAD

**Issue by rominronin** [tomatophp/filament-translations#3]
By default the Translation resource is shown in the sidebar, to override this we cloned the resource and used the shouldRegisterNavigation method (in our use case, not all users should have access to the resource link or its pages).

By cloning the resource however, we ran into the issue that pest tests no longer worked:

<img width="790" alt="image" src="https://github.com/tomatophp/filament-translations/assets/7344944/94b1a576-6de2-4a61-9ced-7eef6c3f9ac1">

I need a way to control the permissions of the translations pages and the sidebar link.

**Comment by 3x1io** [comment]
we will add this feature on the next release thanks for your support.

**Comment by rominronin** [comment]
Thank you. What kind of time frame do you think that will be?

**Comment by 3x1io** [comment]
it's done now on v1.0.4

you can hide navigation from config just change this to false

```php
'register_navigation' => false,
```
