### ISSUE TITLE
[Bug]: file_put_contents(...): Failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by nocodelab** [tomatophp/filament-translations#33]
### What happened?

Hello guys, the package seems great but I'm not able to use it on a fresh Filament 3 installation.
After I run the install command (php artisan filament-translations:install) I have this error with a missing blade file.
I use Laravel Sail.

### How to reproduce the bug

composer require tomatophp/filament-translations
php artisan filament-translations:install

### Package Version

2.0.3

### PHP Version

8.2

### Laravel Version

11

### Which operating systems does with happen with?

macOS

**Comment by 3x1io** [comment]
hi @nocodelab can you share the full error?

**Comment by 3x1io** [comment]
okay it's not a problem on the package it's just a view caches you can try

```bash
php artisan optimize:clear
```

**Comment by nocodelab** [comment]
Correct :)
Sorry for bothering you!

**Comment by nocodelab** [comment]
False alarm :)
