### ISSUE TITLE
Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by mrvnklm** [tomatophp/filament-translations#5]
Scanning for new languages always causes `Maximum execution time of 30 seconds exceeded`

Of course I could just increase execution time but I think it would make more sense to just do it for the specified command or have the option to let the queue do that work?

Besides, why is that plugin not listed on filaments plugin page?

**Comment by 3x1io** [comment]
Hi, @mrvnklm thanks for your report we are working to move it to queue as option on config and we will add a command for scan full app and scan for selected path on the next version.

**Comment by mrvnklm** [comment]
Nice sounds good, looking forward to it!

**Comment by 3x1io** [comment]
fixed on v1.0.5
