### ISSUE TITLE
Feature: button to manually add translation

### ISSUE THREAD

**Issue by mrvnklm** [tomatophp/filament-translations#9]
Would be nice to manually add a translation key, because sometime theres some keys that are generated on the fly so they cant be recognized by scanning the files.

**Comment by 3x1io** [comment]
@mrvnklm oh! good idea, i will try to add this feature on the next release

**Comment by 3x1io** [comment]
@mrvnklm another good idea thanks

**Comment by 3x1io** [comment]
### Allow Create Button to Create New Language

If you want to allow the user to create a new language, you need to add the following to your panel provider:

```php
$panel->plugin(\TomatoPHP\FilamentTranslations\FilamentTranslationsPlugin::make()->allowCreate())
```

check v1.0.12
